# lightning.pytorch==2.3.2
seed_everything: 10
trainer:
  accelerator: auto
  strategy: auto
  devices: [3]
  num_nodes: 1
  precision: null
  logger: true
  callbacks: null
  fast_dev_run: false
  max_epochs: 300
  min_epochs: 0
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 32
  gradient_clip_val: 0.01
  gradient_clip_algorithm: norm
  deterministic: true
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: simple
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: experiments/Restormer_L1Loss
ckpt_path: C:\Users\yxq\project\PL\LitCLI\experiments\Restormer\lightning_logs\version_0\checkpoints\epoch=37-val_psnr=37.0174.ckpt
model: 
  class_path: IRLitModule
  init_args:
    net: 
      class_path: Restormer
      init_args:
        inp_channels: 1
        out_channels: 1
        dim: 48
        num_blocks: [4,6,6,8]
        num_refinement_blocks: 4
        heads: [1,2,4,8]
        ffn_expansion_factor: 2.66
        bias: False
        LayerNorm_type: BiasFree
        dual_pixel_task: False
    losses:
      class_path: yxq.model.loss.L1Loss
      init_args:
        loss_weight: 1
        reduction: mean
    psnr:
      class_path: PeakSignalNoiseRatio
    ssim:
      class_path: StructuralSimilarityIndexMeasure
      init_args:
        data_range: 1.0
    optimizer:
      class_path: AdamW
      init_args:
        lr: 3e-4
        weight_decay: 1e-4
        betas: [0.9, 0.999]
    scheduler:
      class_path: CosineAnnealingLR
      init_args:
        T_max: 300000
        eta_min: 1e-7
    lr_scheduler_config:
      interval: step
      frequency: 1
      monitor: val_loss
      strict: true
data: 
  class_path: IRLitDataModule
  init_args:
    train:
      dataset:
        flag: 0   # 0: grayscale, 1: color, -1: unchanged
        lq_dir: ..\datasets\train\DUKE\lq256.lmdb
        gt_dir: ..\datasets\train\DUKE\gt256.lmdb
      dataloader:
        batch_size: 1
        pin_memory: true
        shuffle: true
        drop_last: true
    val:
      dataset:
        flag: 0
        lq_dir: ..\datasets\val\DUKE\lq512.lmdb
        gt_dir: ..\datasets\val\DUKE\gt512.lmdb
      dataloader:
        batch_size: 1
        pin_memory: true
        shuffle: false
        drop_last: false
    test:
      - dataset:
          flag: 0
          lq_dir: ..\datasets\val\DUKE\lq.lmdb
          gt_dir: ..\datasets\val\DUKE\gt.lmdb
          patch_size: [1200, 1800]
        dataloader:
          batch_size: 1
          pin_memory: true
          shuffle: false
          drop_last: false
      - dataset:
          flag: 0
          lq_dir: ..\datasets\val\DUKE\lq512.lmdb
          gt_dir: ..\datasets\val\DUKE\gt512.lmdb
        dataloader:
          batch_size: 2
          pin_memory: true
          shuffle: false
          drop_last: false
      - dataset:
          flag: 0
          lq_dir: ..\datasets\val\DUKE\lq256.lmdb
          gt_dir: ..\datasets\val\DUKE\gt256.lmdb
        dataloader:
          batch_size: 8
          pin_memory: true
          shuffle: false
          drop_last: false
    predict:
      dataset:
        flag: 0
        dir: ..\datasets\val\DUKE\lq512
      dataloader:
        batch_size: 1
        pin_memory: true
        shuffle: false
        drop_last: false
